// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: stubs.proto

package stubs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numbers []int32 `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
}

func (x *NumberChunk) Reset() {
	*x = NumberChunk{}
	mi := &file_mapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberChunk) ProtoMessage() {}

func (x *NumberChunk) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberChunk.ProtoReflect.Descriptor instead.
func (*NumberChunk) Descriptor() ([]byte, []int) {
	return file_mapper_proto_rawDescGZIP(), []int{0}
}

func (x *NumberChunk) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type MapperResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *MapperResponse) Reset() {
	*x = MapperResponse{}
	mi := &file_mapper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapperResponse) ProtoMessage() {}

func (x *MapperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapperResponse.ProtoReflect.Descriptor instead.
func (*MapperResponse) Descriptor() ([]byte, []int) {
	return file_mapper_proto_rawDescGZIP(), []int{1}
}

func (x *MapperResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_mapper_proto protoreflect.FileDescriptor

var file_mapper_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x0b, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x56,
	0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x45, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x47, 0x6f, 0x2f, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mapper_proto_rawDescOnce sync.Once
	file_mapper_proto_rawDescData = file_mapper_proto_rawDesc
)

func file_mapper_proto_rawDescGZIP() []byte {
	file_mapper_proto_rawDescOnce.Do(func() {
		file_mapper_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapper_proto_rawDescData)
	})
	return file_mapper_proto_rawDescData
}

var file_mapper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mapper_proto_goTypes = []any{
	(*NumberChunk)(nil),    // 0: protoBuffer.NumberChunk
	(*MapperResponse)(nil), // 1: protoBuffer.MapperResponse
}
var file_mapper_proto_depIdxs = []int32{
	0, // 0: protoBuffer.MapperService.ProcessChunk:input_type -> protoBuffer.NumberChunk
	1, // 1: protoBuffer.MapperService.ProcessChunk:output_type -> protoBuffer.MapperResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mapper_proto_init() }
func file_mapper_proto_init() {
	if File_mapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mapper_proto_goTypes,
		DependencyIndexes: file_mapper_proto_depIdxs,
		MessageInfos:      file_mapper_proto_msgTypes,
	}.Build()
	File_mapper_proto = out.File
	file_mapper_proto_rawDesc = nil
	file_mapper_proto_goTypes = nil
	file_mapper_proto_depIdxs = nil
}
