// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: stubs.proto

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MapperService_ProcessChunk_FullMethodName = "/protoBuffer.MapperService/ProcessChunk"
)

// MapperServiceClient is the client API for MapperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MapperServiceClient interface {
	ProcessChunk(ctx context.Context, in *NumberChunk, opts ...grpc.CallOption) (*MapperResponse, error)
}

type mapperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMapperServiceClient(cc grpc.ClientConnInterface) MapperServiceClient {
	return &mapperServiceClient{cc}
}

func (c *mapperServiceClient) ProcessChunk(ctx context.Context, in *NumberChunk, opts ...grpc.CallOption) (*MapperResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapperResponse)
	err := c.cc.Invoke(ctx, MapperService_ProcessChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapperServiceServer is the server API for MapperService service.
// All implementations must embed UnimplementedMapperServiceServer
// for forward compatibility.
type MapperServiceServer interface {
	ProcessChunk(context.Context, *NumberChunk) (*MapperResponse, error)
	mustEmbedUnimplementedMapperServiceServer()
}

// UnimplementedMapperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMapperServiceServer struct{}

func (UnimplementedMapperServiceServer) ProcessChunk(context.Context, *NumberChunk) (*MapperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessChunk not implemented")
}
func (UnimplementedMapperServiceServer) mustEmbedUnimplementedMapperServiceServer() {}
func (UnimplementedMapperServiceServer) testEmbeddedByValue()                       {}

// UnsafeMapperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapperServiceServer will
// result in compilation errors.
type UnsafeMapperServiceServer interface {
	mustEmbedUnimplementedMapperServiceServer()
}

func RegisterMapperServiceServer(s grpc.ServiceRegistrar, srv MapperServiceServer) {
	// If the following call pancis, it indicates UnimplementedMapperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MapperService_ServiceDesc, srv)
}

func _MapperService_ProcessChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapperServiceServer).ProcessChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapperService_ProcessChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapperServiceServer).ProcessChunk(ctx, req.(*NumberChunk))
	}
	return interceptor(ctx, in, info, handler)
}

// MapperService_ServiceDesc is the grpc.ServiceDesc for MapperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoBuffer.MapperService",
	HandlerType: (*MapperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessChunk",
			Handler:    _MapperService_ProcessChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stubs.proto",
}
